config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :tasks

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :task
    belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    has_many :comments
    validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.tasks.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = current_user.tasks.find(params[:id]) 
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :due_date, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def nav_link(text, path, method)
        if current_page?(path)
             content_tag(:li, class: "nav-items active") do
                 link_to(path, class: "nav-link", method: method) do
                     sanitize(text) + content_tag(:span, "(current)", class: "sr-only")
                 end
             end
         else
             content_tag(:li, class: "nav-items") do
                 link_to(text, path, class: "nav-link", method: method)
             end
        end   
     end
end
 

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<div id="home">
  <h1>Home Page</h1>
  <%= link_to "Tasks", tasks_url %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.3.3/dist/css/uikit.min.css" />
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <%= link_to  "Task App", root_path, class: "navbar-brand" %>

      <button id="hamburger" class="navbar-toggler hamburger hamburger--stand" style="outline: none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="hamburger-box">
          <span class="hamburger-inner"></span>
        </span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? then %>
              <%= nav_link "Home", root_path, :get %>
              <%= nav_link "Task", tasks_path, :get %>
              <%= nav_link "Logout", destroy_user_session_path, :delete %>
            <% else %>
              <%= nav_link "Home", root_path, :get %>
              <%= nav_link "Sign Up", new_user_registration_path, :get  %>
              <%= nav_link "Login", new_user_session_path, :get %>
          <% end %>
        </ul>
      </div>

    </nav>

    <div id="content" style="margin-top: 100px" class="uk-container">
      <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
      <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
      <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
      
      <%= yield %>
    </div>

    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.3.3/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.3.3/dist/js/uikit-icons.min.js"></script>
    <script>
      //Hamburger Nav Scripts
       // Nav Overlay toggle
      function toggleMenu() {
        // Active class toggle
        document.getElementById("hamburger").classList.toggle("is-active");
      }
      // Toggle menu open close
      document.getElementById("hamburger").addEventListener("click", toggleMenu);
    </script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :due_date %>
    <%= form.datetime_select :due_date %>
  </div>
  <div class="field">
    <%= form.label :priority %>
    <%= form.number_field :priority %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>


app/views/tasks/_task.html.erb
<div class="task">
  <p>
    <strong>Task ID:</strong>
    <%= task.id %>
  </p>
  <p>
    <strong>Title:</strong>
    <%= link_to_unless_current task.title, task %>
  </p>
  <p>
    <strong>Due date:</strong>
    <%= task.due_date %>
  </p>
  <p>
    <strong>Priority:</strong>
    <%= task.priority %>
  </p>
  <p>
    <strong>USER Email:</strong>
    <%= task.user.email %>
  </p>
</div>
<br>
<br>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>
<%= render 'form', task: @task %>
<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<%= "Logged in as #{current_user.email}" %>

<h1>Tasks</h1>
<%= render @tasks %>

<br>
<%= link_to  "Home", root_url %> |
<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<%= render @task %>
<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %> |
<%= link_to 'Delete', task_path(@task), method: :delete, data: { confirm: 'Are you sure?' } %>